# Generated by Django 5.1.3 on 2025-07-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Concessionaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concessionaria',
            name='codice_fiscale',
            field=models.CharField(default=None, max_length=16, unique=True),
            preserve_default=False,
        ),
    ]
