# Generated by Django 5.2.4 on 2025-07-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Concessionaria', '0002_concessionaria_codice_fiscale'),
    ]

    operations = [
        migrations.AddField(
            model_name='concessionaria',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
