# Generated by Django 5.2.4 on 2025-07-24 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Concessionaria', '0003_concessionaria_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concessionaria',
            name='email',
        ),
        migrations.RemoveField(
            model_name='concessionaria',
            name='indirizzo',
        ),
        migrations.RemoveField(
            model_name='concessionaria',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='concessionaria',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='concessionaria',
            name='password',
        ),
        migrations.RemoveField(
            model_name='concessionaria',
            name='telefono',
        ),
        migrations.AddField(
            model_name='concessionaria',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='concessionaria_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
