# Generated by Django 5.2.4 on 2025-07-24 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Concessionaria', '0004_remove_concessionaria_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcessionariaExtendModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_concessionaria', models.CharField(max_length=255)),
                ('indirizzo', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='concessionaria_extend', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
