# Generated by Django 5.2.4 on 2025-07-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Concessionaria', '0005_concessionariaextendmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='concessionaria',
            name='indirizzo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='concessionaria',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='ConcessionariaExtendModel',
        ),
    ]
