# Generated by Django 5.2.4 on 2025-08-18 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Concessionaria', '0006_concessionaria_indirizzo_concessionaria_telefono_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryAffittate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affittante_username', models.CharField(blank=True, max_length=255, null=True)),
                ('auto_marca', models.CharField(blank=True, max_length=255, null=True)),
                ('auto_modello', models.CharField(blank=True, max_length=255, null=True)),
                ('data_inizio', models.DateTimeField()),
                ('data_fine', models.DateTimeField()),
                ('prezzo_affitto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('concessionaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concessionaria_affitto', to='Concessionaria.concessionaria')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryVendute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquirente_username', models.CharField(blank=True, max_length=255, null=True)),
                ('auto_marca', models.CharField(blank=True, max_length=255, null=True)),
                ('auto_modello', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('prezzo_vendita', models.DecimalField(decimal_places=2, max_digits=10)),
                ('concessionaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concessionaria_vendita', to='Concessionaria.concessionaria')),
            ],
        ),
    ]
