# Generated by Django 5.2.4 on 2025-08-19 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Concessionaria', '0007_historyaffittate_historyvendute'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historyaffittate',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historyvendute',
            name='auto_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historyaffittate',
            name='concessionaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concessionaria_affitto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historyvendute',
            name='concessionaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concessionaria_vendita', to=settings.AUTH_USER_MODEL),
        ),
    ]
