# Generated by Django 5.2.4 on 2025-08-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Concessionaria', '0008_historyaffittate_data_historyvendute_auto_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyaffittate',
            name='auto_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
