# Generated by Django 5.2.4 on 2025-07-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utente', '0002_userextendmodel_usermodelban_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextendmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
