# Generated by Django 5.2.4 on 2025-08-06 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utente', '0003_userextendmodel_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Segnalazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('data_segnalazione', models.DateTimeField(auto_now_add=True)),
                ('segnalato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segnalazioni_ricevute', to=settings.AUTH_USER_MODEL)),
                ('segnalatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segnalazioni_inviate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
