# Generated by Django 5.2.4 on 2025-08-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utente', '0004_segnalazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextendmodel',
            name='data_fine_blocco_prenotazioni',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userextendmodel',
            name='data_inizio_blocco_prenotazioni',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='segnalazione',
            name='motivo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
