# Generated by Django 5.1.3 on 2025-07-16 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_possessore', models.PositiveIntegerField()),
                ('tipologia_possessore', models.CharField(choices=[(0, 'Utente'), (1, 'Concessionaria')], max_length=50)),
                ('marca', models.CharField(max_length=100)),
                ('modello', models.CharField(max_length=100)),
                ('cilindrata', models.PositiveIntegerField()),
                ('carburante', models.IntegerField(choices=[(0, 'Benzina'), (1, 'Diesel'), (2, 'Elettrico'), (3, 'Ibrido Benzina'), (4, 'Ibrido Diesel'), (5, 'GPL'), (6, 'Metano')])),
                ('cambio', models.IntegerField(choices=[(0, 'Manuale'), (1, 'Automatico'), (2, 'Semi-automatico')])),
                ('trazione', models.IntegerField(choices=[(0, 'Anteriore'), (1, 'Posteriore'), (2, 'Integrale')])),
                ('anno', models.PositiveIntegerField()),
                ('disponibilita', models.IntegerField(choices=[(0, 'Vendita'), (1, 'Affitto'), (2, 'Vendita e Affitto'), (3, 'Contrattazione'), (4, 'Prenotazione'), (5, 'Sconosciuto')], default=5)),
                ('chilometraggio', models.PositiveIntegerField()),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('immagine', models.ImageField(blank=True, null=True, upload_to='Auto/')),
            ],
        ),
        migrations.CreateModel(
            name='AutoVenditaAffitto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prezzo_vendita', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prezzo_affitto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('venduta', models.BooleanField(default=False)),
                ('affittata', models.BooleanField(default=False)),
                ('data_pubblicazione', models.DateTimeField(auto_now_add=True)),
                ('venditore', models.PositiveIntegerField()),
                ('acquirente', models.PositiveIntegerField(blank=True, null=True)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vendita', to='Auto.auto')),
            ],
        ),
    ]
