# Generated by Django 5.1.3 on 2025-07-16 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='disponibilita',
            field=models.IntegerField(choices=[(0, 'Vendita'), (1, 'Affitto'), (2, 'Vendita e Affitto'), (3, 'Contrattazione'), (4, 'In Contrattazione (Venditore)'), (5, 'In Contrattazione (Acquirente)'), (6, 'Prenotazione'), (7, 'Sconosciuto')], default=5),
        ),
        migrations.AlterField(
            model_name='autovenditaaffitto',
            name='auto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VenditaAffitto', to='Auto.auto'),
        ),
        migrations.CreateModel(
            name='AutoContrattazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prezzo_iniziale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prezzo_attuale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prezzo_finale', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_inizio', models.DateTimeField(auto_now_add=True)),
                ('data_fine', models.DateTimeField(blank=True, null=True)),
                ('venditore', models.PositiveIntegerField()),
                ('acquirente', models.PositiveIntegerField(blank=True, null=True)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Contrattazione', to='Auto.auto')),
            ],
        ),
    ]
