# Generated by Django 5.1.3 on 2025-07-17 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auto', '0002_alter_auto_disponibilita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autocontrattazione',
            name='auto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrattazione', to='Auto.auto'),
        ),
        migrations.CreateModel(
            name='AutoAffitto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prezzo_affitto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_inizio', models.DateTimeField()),
                ('data_fine', models.DateTimeField()),
                ('affittata', models.BooleanField(default=False)),
                ('data_pubblicazione', models.DateTimeField(auto_now_add=True)),
                ('affittante', models.PositiveIntegerField()),
                ('affittuario', models.PositiveIntegerField(blank=True, null=True)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affitto', to='Auto.auto')),
            ],
        ),
        migrations.CreateModel(
            name='AutoVendita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prezzo_vendita', models.DecimalField(decimal_places=2, max_digits=10)),
                ('venduta', models.BooleanField(default=False)),
                ('data_pubblicazione', models.DateTimeField(auto_now_add=True)),
                ('venditore', models.PositiveIntegerField()),
                ('acquirente', models.PositiveIntegerField(blank=True, null=True)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendita', to='Auto.auto')),
            ],
        ),
        migrations.DeleteModel(
            name='AutoVenditaAffitto',
        ),
    ]
