# Generated by Django 5.1.3 on 2025-07-18 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auto', '0003_alter_autocontrattazione_auto_autoaffitto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autoaffitto',
            old_name='affittante',
            new_name='affittante_id',
        ),
        migrations.RenameField(
            model_name='autocontrattazione',
            old_name='acquirente',
            new_name='acquirente_id',
        ),
        migrations.RenameField(
            model_name='autocontrattazione',
            old_name='venditore',
            new_name='venditore_id',
        ),
        migrations.RemoveField(
            model_name='autovendita',
            name='acquirente',
        ),
        migrations.RemoveField(
            model_name='autovendita',
            name='venduta',
        ),
        migrations.AddField(
            model_name='autoaffitto',
            name='affittante_tipologia',
            field=models.CharField(choices=[(0, 'Utente'), (1, 'Concessionaria')], default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autoaffitto',
            name='affittuario_tipologia',
            field=models.CharField(blank=True, choices=[(0, 'Utente'), (1, 'Concessionaria')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='autocontrattazione',
            name='acquirente_tipologia',
            field=models.CharField(blank=True, choices=[(0, 'Utente'), (1, 'Concessionaria')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='autocontrattazione',
            name='venditore_tipologia',
            field=models.CharField(choices=[(0, 'Utente'), (1, 'Concessionaria')], default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AutoPrenotazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inizio', models.DateTimeField()),
                ('data_fine', models.DateTimeField()),
                ('prenotata', models.BooleanField(default=False)),
                ('data_pubblicazione', models.DateTimeField(auto_now_add=True)),
                ('proprietario_id', models.PositiveIntegerField()),
                ('proprietario_tipologia', models.CharField(choices=[(0, 'Utente'), (1, 'Concessionaria')], max_length=50)),
                ('prenotante_id', models.PositiveIntegerField(blank=True, null=True)),
                ('prenotante_tipologia', models.CharField(blank=True, choices=[(0, 'Utente'), (1, 'Concessionaria')], max_length=50, null=True)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prenotazione', to='Auto.auto')),
            ],
        ),
    ]
