# Generated by Django 5.2.4 on 2025-07-26 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auto', '0004_rename_affittante_autoaffitto_affittante_id_and_more'),
        ('Utente', '0003_userextendmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='user_auto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='possessore_auto', to='Utente.userextendmodel'),
            preserve_default=False,
        ),
    ]
