# Generated by Django 5.2.4 on 2025-07-26 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auto', '0005_auto_user_auto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='user_auto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='possessore_auto', to=settings.AUTH_USER_MODEL),
        ),
    ]
