# Generated by Django 5.2.4 on 2025-07-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auto', '0006_alter_auto_user_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoaffitto',
            name='data_fine',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='autoaffitto',
            name='data_inizio',
            field=models.DateTimeField(null=True),
        ),
    ]
