# Generated by Django 5.2.4 on 2025-07-27 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auto', '0007_alter_autoaffitto_data_fine_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autoaffitto',
            old_name='affittante_id',
            new_name='affittante',
        ),
        migrations.RemoveField(
            model_name='autoaffitto',
            name='affittante_tipologia',
        ),
    ]
