# Generated by Django 5.2.4 on 2025-08-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auto', '0009_commento_risposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoaffitto',
            name='affittante',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
