# Generated by Django 5.2.4 on 2025-08-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auto', '0010_alter_autoaffitto_affittante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='disponibilita',
            field=models.IntegerField(choices=[(0, 'Vendita'), (1, 'Affitto'), (2, 'Vendita e Affitto'), (3, 'Contrattazione'), (4, 'In Contrattazione (Venditore)'), (5, 'In Contrattazione (Acquirente)'), (6, 'Prenotata'), (7, 'Affittata'), (8, 'Sconosciuto')], default=5),
        ),
    ]
