# Generated by Django 5.2.4 on 2025-08-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auto', '0011_alter_auto_disponibilita'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='disponibilita_prec',
            field=models.IntegerField(choices=[(0, 'Vendita'), (1, 'Affitto'), (2, 'Vendita e Affitto'), (3, 'Contrattazione'), (4, 'In Contrattazione (Venditore)'), (5, 'In Contrattazione (Acquirente)'), (6, 'Prenotata'), (7, 'Affittata'), (8, 'Sconosciuto')], default=8),
        ),
        migrations.AlterField(
            model_name='auto',
            name='disponibilita',
            field=models.IntegerField(choices=[(0, 'Vendita'), (1, 'Affitto'), (2, 'Vendita e Affitto'), (3, 'Contrattazione'), (4, 'In Contrattazione (Venditore)'), (5, 'In Contrattazione (Acquirente)'), (6, 'Prenotata'), (7, 'Affittata'), (8, 'Sconosciuto')], default=8),
        ),
    ]
