# Generated by Django 5.2.4 on 2025-08-07 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auto', '0012_auto_disponibilita_prec_alter_auto_disponibilita'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoListaAffitto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prezzo_affitto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pubblicazione', models.DateTimeField(auto_now_add=True)),
                ('affittante', models.PositiveIntegerField()),
                ('affittante_tipologia', models.CharField(choices=[(0, 'Utente'), (1, 'Concessionaria')], max_length=50)),
                ('data_inizio', models.DateTimeField(null=True)),
                ('data_fine', models.DateTimeField(null=True)),
                ('lista_auto_affitto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_affitto', to='Auto.autoaffitto')),
            ],
        ),
    ]
