# Generated by Django 5.2.4 on 2025-08-20 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auto', '0013_autolistaaffitto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='autocontrattazione',
            name='stato',
            field=models.CharField(choices=[('in_corso', 'In corso'), ('accettata', 'Accettata'), ('rifiutata', 'Rifiutata'), ('conclusa', 'Conclusa')], default='in_corso', max_length=20),
        ),
        migrations.CreateModel(
            name='ContrattazioneOfferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prezzo_offerto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_offerta', models.DateTimeField(auto_now_add=True)),
                ('ruolo', models.IntegerField(choices=[(0, 'Acquirente'), (1, 'Venditore')])),
                ('contrattazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerte', to='Auto.autocontrattazione')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
