# Generated by Django 5.2.4 on 2025-08-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auto', '0014_autocontrattazione_stato_contrattazioneofferta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autocontrattazione',
            name='stato',
            field=models.IntegerField(choices=[(0, 'Disponibile alla contrattazione'), (1, 'Venditore in contrattazione'), (2, 'Acquirente in contrattazione')], default=0),
        ),
    ]
