# Generated by Django 5.2.4 on 2025-07-18 21:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_object_id', models.PositiveIntegerField()),
                ('receiver_object_id', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read', models.BooleanField(default=False)),
                ('receiver_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='contenttypes.contenttype')),
                ('sender_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
